apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pdu9i8824-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pdu9i8824-python 
  name: pdu9i8824-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pdu9i8824-python 
